### ISSUE TITLE
ValueError in test_mod.py

### ISSUE THREAD

**Issue by dljzx** [Shobhit20/Image-Captioning#8]
When I was testing the program I met error like this:
File "E:\github\Image-Captioning\test_mod.py", line 10, in process_caption
terminate_id = tokens.index('end')
ValueError: 'end' is not in list
How can I solve it?

**Comment by dljzx** [comment]
process_caption terminate_id = tokens.index('<end>')
ValueError:"<end>"is not in list

**Comment by shirshak55** [comment]
@dljzx did u solved it?

**Comment by shirshak55** [comment]
@dljzx please let me know how did u solved it.

**Comment by dljzx** [comment]
I modified the code accordingly. But the training result was still bad.
https://github.com/anuragmishracse/caption_generator/blob/master/caption_generator/test_model.py




@dljzx<https://github.com/dljzx> please let me know how did u solved it.

**Comment by shirshak55** [comment]
@dljzx hmm which file is that? seems like we need to update test_mod file isn't it?

**Comment by shirshak55** [comment]
hmm I wonder how they got the <end> in text because it seems it is just array of words right?

**Comment by shirshak55** [comment]
by the way is it giving u bad results like
Naked gardening packages cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball packages cannonball cannonball cannonball packages cannonball metropolitain surfs surfs surfs

**Comment by dljzx** [comment]
It is the reference code that author used so I think it is fine. But the training result is terrible. You can see anther question I raised.
________________________________
发件人: Shirshak Bajgain <notifications@github.com>
发送时间: Sunday, June 16, 2019 11:59:26 AM
收件人: Shobhit20/Image-Captioning
抄送: dljzx; Mention
主题: Re: [Shobhit20/Image-Captioning] ValueError in test_mod.py (#8)


@dljzx<https://github.com/dljzx> hmm which file is that? seems like we need to update test_mod file isn't it?

―

**Comment by shirshak55** [comment]
Hmm wasted lot of time in this project :) Seems like they even didn't tested on their own test images. Because I tried with their example and it shows garbage

**Comment by dljzx** [comment]
Exactly, and I don’t know why...maybe the way that I solved value error is incorrect.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Shirshak Bajgain <notifications@github.com>
发送时间: Sunday, June 16, 2019 12:02:59 PM
收件人: Shobhit20/Image-Captioning
抄送: dljzx; Mention
主题: Re: [Shobhit20/Image-Captioning] ValueError in test_mod.py (#8)


by the way is it giving u bad results like
Naked gardening packages cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball cannonball packages cannonball cannonball cannonball packages cannonball metropolitain surfs surfs surfs

―

**Comment by shirshak55** [comment]
check this. It is far better than this 

https://www.tensorflow.org/beta/tutorials/text/image_captioning

Wasted hell lot of time and seems like this is too old and not cared :)
